### PR TITLE
Add now param

### PR DESCRIPTION
**Pull request by blanchg**
Implemented
Documentation added
Tests added

### CODE REVIEW

**Comment by blanchg** [comment]
This pull request is for Issue #13

**Comment by danez** [comment]
Nice thanks

**Comment by danez** [comment]
I will release soon. I was investigating why the tests are failing now, but figured that it is because of DST which was enabled last weekend here and the test tests +/- 5days 🙄 😂

**Comment by blanchg** [comment]
Oh ooops 😀

**Pull request merged**
